name: manually build ndk-pkg packages

on:
  workflow_dispatch:
    inputs:

      package-name:
        description: input the package name to be built
        required: true
        default: libz

      target-api:
        description: choose the min sdk api level to be built with
        type: choice
        options:
          - '35'
          - '34'
          - '33'
          - '32'
          - '31'
          - '30'
          - '29'
          - '28'
          - '27'
          - '26'
          - '25'
          - '24'
          - '23'
          - '22'
          - '21'

      target-abis:
        description: input android abis to be built for
        required: true
        default: arm64-v8a,armeabi-v7a,x86_64,x86

      profile:
        description: choose a build profile
        type: choice
        options:
          - release
          - debug

      bundle-type:
        description: choose a bundle type
        type: choice
        options:
          - .tar.xz
          - .tar.lz
          - .tar.gz
          - .tar.bz2
          - .zip

      log-level:
        description: choose a log-level
        type: choice
        options:
          - ''
          - '-q'
          - '-v'
          - '-vv'

      static:
        description: create fully statically linked executables
        type: choice
        options:
          - ''
          - '--static'

      generate-maven-repo:
        description: generate maven local repository bundle
        type: boolean
        default: false

      maven-group-id:
        description: input the maven groupId, default is com.fpliu.ndk.pkg.prefab.android.<API>

jobs:
  build:

    runs-on: ubuntu-latest

    container: ubuntu:24.04

    steps:
      - run: apt -y update
      - run: apt -y install curl

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg update
      - run: ./ndk-pkg install android-${{ github.event.inputs.target-api }}-${{ github.event.inputs.target-abis }}/${{ github.event.inputs.package-name }} --profile=${{ github.event.inputs.profile }} ${{ github.event.inputs.static }} ${{ github.event.inputs.log-level }}

      - name: pack
        run: |
          set -ex
          for item in $(./ndk-pkg ls-installed)
          do
              ./ndk-pkg bundle "$item" ${{ github.event.inputs.bundle-type }}
          done

      - run: ls

      - run: du -sh *${{ github.event.inputs.bundle-type }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package-name }}---android-${{ github.event.inputs.target-api }}-${{ github.event.inputs.target-abis }}.${{ github.event.inputs.profile }}${{ github.event.inputs.bundle-type }}
          path: ./*${{ github.event.inputs.bundle-type }}





      - if: ${{ github.event.inputs.generate-maven-repo == 'true' }}
        name: generate maven local repository
        run: |
          set -ex

          export NDKPKG_XTRACE=1

          GROUPID='${{ github.event.inputs.maven-group-id }}'

          [ -z "$GROUPID" ] && GROUPID='com.fpliu.ndk.pkg.prefab.android.${{ github.event.inputs.target-api }}'

          ABIS="${{ github.event.inputs.target-abis }}"

          ABI="${ABIS%%,*}"

          for PKGNAME in $(./ndk-pkg ls-installed | cut -d/ -f2 | sort | uniq)
          do
              if [ -d "$HOME/.ndk-pkg/installed/android-${{ github.event.inputs.target-api }}-$ABI/$PKGNAME/include" ] ; then
                  ./ndk-pkg deploy android-${{ github.event.inputs.target-api }}-${{ github.event.inputs.target-abis }}/$PKGNAME --local=maven-local-repository-bundle --groupId="$GROUPID"
              else
                  echo "no dev files."
              fi
          done

          if [ -d maven-local-repository-bundle ] ; then
              ~/.ndk-pkg/uppm/installed/bsdtar/bin/bsdtar cvaf maven-local-repository-bundle.tar.xz maven-local-repository-bundle
          fi

      - if: ${{ github.event.inputs.generate-maven-repo == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package-name }}---android-${{ github.event.inputs.target-api }}-${{ github.event.inputs.target-abis }}-maven-local-repository-bundle.tar.xz
          path: maven-local-repository-bundle.tar.xz
